# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PMCode
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/PMCode" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
#dribbble_username:
facebook_username: jekyll
#flickr_username:
#instagram_username:
#linkedin_username:
#pinterest_username:
#youtube_username:
#googleplus_username:
rss: RSS PMCode
#google_analytics: id

#author: global author information
#logo: /assets/image/your-company-logo.jpg
#lang: es_ES (idioma del sitio)
#social:
#name: if the user or organization name differs from the site's name(espaciado con respecto a Social)
#link:(espaciado con respecto a Social)
#- https://twitter.com/PMCode (espaciado con respecto a Link)
# ... (Mas redes sociales)
#date_modified: prioridad para la salida date_modified en JSON-LD (espaciado con respecto a Social)
#google_site_verification: (for verifying ownership via Google webmaster tools)

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
collections:
  ayuda:
    output: true
    permalink: /:collection/:name/
defaults:
 - scope:
     path: ""
     type: ayuda
   values:
     layout: ayuda
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
